# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

backward_ll_cpp <- function(Gamma, p) {
    .Call(`_hmm_backward_ll_cpp`, Gamma, p)
}

backward_prob_cpp <- function(Gamma, p) {
    .Call(`_hmm_backward_prob_cpp`, Gamma, p)
}

#' forward_ll_cpp
#'
#' @description Calculate matrix of forward log-probabilities for a given data set and parameters in a HMM
#'
#' @param Gamma A matrix of transition log-probabilities for the underlying Markov chain
#' @param p A matrix of observation log-probabilites, i.e. where the i,j'th entry is the log-likelihood of observing x_j given the hidden state is i
#' @param delta A vector of starting log-probabilites, i.e. the log of the distribution of the first hidden state
#'
#' @output An m x n matrix of forward log-probabilities i.e. where the i,j'th entry is the likelihood of observing the first j observations and the j'th hidden state is i
forward_ll_cpp <- function(Gamma, p, delta) {
    .Call(`_hmm_forward_ll_cpp`, Gamma, p, delta)
}

#' forward_prob_cpp
#'
#' @description Calculate matrix of forward probabilities for a given data set and parameters in a HMM
#'
#' @param Gamma A matrix of transition probabilities for the underlying Markov chain
#' @param p A matrix of observation probabilites, i.e. where the i,j'th entry is the likelihood of observing x_j given the hidden state is i
#' @param delta A vector of starting probabilites, i.e. the distribution of the first hidden state
#'
#' @output An m x n matrix of forward probabilities i.e. where the i,j'th entry is the likelihood of observing the first j observations and the j'th hidden state is i
forward_prob_cpp <- function(Gamma, p, delta) {
    .Call(`_hmm_forward_prob_cpp`, Gamma, p, delta)
}

