# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

backward_ll_cpp <- function(Gamma, p) {
    .Call(`_hmm_backward_ll_cpp`, Gamma, p)
}

backward_prob_cpp <- function(Gamma, p) {
    .Call(`_hmm_backward_prob_cpp`, Gamma, p)
}

forward_ll_cpp <- function(Gamma, p, delta) {
    .Call(`_hmm_forward_ll_cpp`, Gamma, p, delta)
}

forward_prob_cpp <- function(Gamma, p, delta) {
    .Call(`_hmm_forward_prob_cpp`, Gamma, p, delta)
}

